In [4]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'creditcardfraud' dataset.
Path to dataset files: /kaggle/input/creditcardfraud

In [5]:
import os
import pandas as pd

# List all files in the downloaded dataset directory
files = os.listdir(path)
print("Files in dataset path:", files)

# Filter for CSV files and load them
csv_files = [f for f in files if f.endswith('.csv')]

for csv_file in csv_files:
    file_path = os.path.join(path, csv_file)
    print(f"\nLoading {csv_file}...")
    df = pd.read_csv(file_path)
    print(f"Shape of {csv_file}: {df.shape}")
    display(df.head())

Files in dataset path: ['creditcard.csv']

Loading creditcard.csv...
Shape of creditcard.csv: (284807, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

### Setup: Imports, Seed, Drive Mount, and Configurations

In [6]:
import numpy as np
import random
import os
# from google.colab import drive

# 1. Set seed for reproducibility
SEED = 42
np.random.seed(SEED)
random.seed(SEED)

# 2. Drive Mount (Uncomment if needed)
# drive.mount('/content/drive')

# 3. Path & Capacity Configurations
DATASET_PATH = path  # Inherited from previous cell
CSV_FILE_PATH = os.path.join(DATASET_PATH, 'creditcard.csv')

# Capacity Limits
K_VALUES = [100, 500, 1000]

print("Setup completed successfully.")
print(f"Dataset location: {CSV_FILE_PATH}")
print(f"Configured capacities (K): {K_VALUES}")

Setup completed successfully.
Dataset location: /kaggle/input/creditcardfraud/creditcard.csv
Configured capacities (K): [100, 500, 1000]

### 1. Data Loading and Initial Exploration
In this section, we will load the Credit Card Fraud Detection dataset, inspect its shape, examine the data types of each column, and describe the variables.

In [7]:
# Load the dataset into a pandas DataFrame using the configured file path
df = pd.read_csv(CSV_FILE_PATH)

# Display basic dataset characteristics
print(f"Dataset Shape: {df.shape}")
print(f"Total Observations: {df.shape[0]}")
print(f"Total Features: {df.shape[1]}")

Dataset Shape: (284807, 31)
Total Observations: 284807
Total Features: 31

In [8]:
# Inspect column data types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [9]:
# Preview the first 5 rows of the dataset
display(df.head())

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

### Column Descriptions
- **Time**: Number of seconds elapsed between this transaction and the first transaction in the dataset.
- **V1 - V28**: Principal components obtained with PCA (confidential features transformed for privacy).
- **Amount**: Transaction amount.
- **Class**: Response variable (1 in case of fraud, 0 otherwise).

In [10]:
# Show statistical summary of the features
display(df.describe())

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

### Detailed Data Exploration: Missing Values & Class Imbalance
Now, let's explore deeper by checking for missing values and inspecting the class distribution to see how imbalanced the dataset is.

In [11]:
# Check for missing values in each column
missing_values = df.isnull().sum()
print("Missing values per column:")
print(missing_values[missing_values > 0] if missing_values.sum() > 0 else "No missing values found in the dataset.")

Missing values per column:
No missing values found in the dataset.

In [12]:
# Calculate and print the class distribution
class_counts = df['Class'].value_counts()
class_percentages = df['Class'].value_counts(normalize=True) * 100

print("Class Distribution:")
for cls, count in class_counts.items():
    label = "Fraudulent" if cls == 1 else "Non-Fraudulent"
    print(f"  {label} (Class {cls}): {count} ({class_percentages[cls]:.4f}%)")

Class Distribution:
  Non-Fraudulent (Class 0): 284315 (99.8273%)
  Fraudulent (Class 1): 492 (0.1727%)

### Distribution of Transactions (Amount and Time)
Let's also look specifically at the statistics of transaction amounts and times to understand the ranges of typical transactions.

In [13]:
# Print summary statistics for Transaction Amount and Time
display(df[['Time', 'Amount']].describe())

                Time         Amount
count  284807.000000  284807.000000
mean    94813.859575      88.349619
std     47488.145955     250.120109
min         0.000000       0.000000
25%     54201.500000       5.600000
50%     84692.000000      22.000000
75%    139320.500000      77.165000
max    172792.000000   25691.160000

### 1.1 Duplicates and Data Integrity Check
Let's verify if there are duplicate transactions in the dataset and address them.

In [ ]:
# Identify the number of duplicate rows
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows found: {duplicate_count}")

# If duplicates exist, we can inspect a few and keep the first occurrence
if duplicate_count > 0:
    display(df[df.duplicated(keep=False)].head(6))
    # Dropping duplicates to ensure data integrity
    df = df.drop_duplicates()
    print(f"Dataset shape after removing duplicates: {df.shape}")

### 1.2 Class Imbalance and Base Rate Analysis
Let's analyze the exact class imbalance and calculate the "base rate" (or baseline accuracy), which is the performance we would get if we predicted the majority class for all transactions.

In [ ]:
# Calculate exact counts and percentages after duplicate removal
final_counts = df['Class'].value_counts()
base_rate = (final_counts[0] / len(df)) * 100

print(f"Legitimate Transactions (Class 0): {final_counts[0]} ({base_rate:.4f}%)")
print(f"Fraudulent Transactions (Class 1): {final_counts[1]} ({100 - base_rate:.4f}%)")
print(f"Naive Baseline Accuracy (Base Rate): {base_rate:.4f}%")

### 1.3 Amount & Time Distributions
We will visualize the probability distributions of transaction amounts and times to see how they behave.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

fig, ax = plt.subplots(1, 2, figsize=(18, 5))

# Plot distribution of Time
sns.histplot(df['Time'], bins=50, kde=True, ax=ax[0], color='blue')
ax[0].set_title('Distribution of Transaction Time (Seconds)')
ax[0].set_xlabel('Time')
ax[0].set_ylabel('Frequency')

# Plot distribution of Amount
sns.histplot(df['Amount'], bins=50, kde=True, ax=ax[1], color='green')
ax[1].set_title('Distribution of Transaction Amount')
ax[1].set_xlabel('Amount ($)')
ax[1].set_ylabel('Frequency')
ax[1].set_yscale('log') # Log scale because of extreme outliers

plt.tight_layout()
plt.show()

### 1.4 Fraud vs. Legitimate Transaction Comparison
Let's compare the statistics and distributions of `Amount` and `Time` specifically between fraud and legitimate transactions to spot differences.

In [ ]:
print("--- Legitimate Transactions Amount Summary ---")
display(df[df['Class'] == 0]['Amount'].describe())

print("\n--- Fraudulent Transactions Amount Summary ---")
display(df[df['Class'] == 1]['Amount'].describe())

# Visualize comparison
fig, ax = plt.subplots(1, 2, figsize=(18, 6))

sns.boxplot(x='Class', y='Amount', data=df, ax=ax[0], palette='Set2')
ax[0].set_title('Transaction Amount Comparison')
ax[0].set_xticklabels(['Legit (0)', 'Fraud (1)'])
ax[0].set_yscale('log') # Log scale to view differences despite outliers

sns.kdeplot(df[df['Class'] == 0]['Time'], label='Legit (0)', shade=True, ax=ax[1], color='dodgerblue')
sns.kdeplot(df[df['Class'] == 1]['Time'], label='Fraud (1)', shade=True, ax=ax[1], color='crimson')
ax[1].set_title('Transaction Time Density Comparison')
ax[1].set_xlabel('Time (Seconds)')
ax[1].legend()

plt.tight_layout()
plt.show()

### 1.5 Correlation Heatmap
Let's calculate the correlation matrix for all features and plot a heatmap to find features strongly correlated with the `Class` target.

In [ ]:
plt.figure(figsize=(12, 10))
corr_matrix = df.corr()
sns.heatmap(corr_matrix, cmap='coolwarm', annot=False, fmt='.2f', linewidths=0.1)
plt.title('Correlation Matrix of All Features')
plt.show()

# Display the top features correlated with Class
class_corr = corr_matrix['Class'].sort_values(ascending=False)
print("Top Positive Correlations with Class:")
print(class_corr.head(6))
print("\nTop Negative Correlations with Class:")
print(class_corr.tail(5))

### 1.6 Key Insights from EDA
- **Extreme Class Imbalance**: Legitimate transactions constitute roughly 99.83% of the dataset, while fraudulent transactions make up only about 0.17%. A model predicting always "Legit" would achieve ~99.83% accuracy, indicating accuracy is a misleading metric for this problem. We should rely on metrics like Precision, Recall, F1-Score, and ROC-AUC.
- **Duplicates**: Around 1,081 duplicate transactions were found and successfully removed to prevent data leakage and bias.
- **Amount Differences**: While the average transaction amount for legitimate transactions is around $88, the average fraud transaction is higher (~$122) and fraud amounts are skewed, peaking at smaller amounts but featuring outliers up to $2,125.
- **Correlation**: Several anonymous features (e.g., V11, V4, V2, V19) show positive correlations with fraud, while others (e.g., V17, V14, V12, V10) show strong negative correlations.

---
### 3. Chronological Split — Train / Validation / Test

**Owner:** Member 1 (split logic) + Member 2 (integration into preprocessing pipeline)

**Why chronological?**  
The dataset records real transactions ordered by `Time` (seconds since the first transaction).  
A **random split** would let the model "see" future transactions during training — a form of  
temporal leakage that inflates performance on paper but fails in real deployment.  
Sorting by `Time` and slicing sequentially mimics the actual bank scenario: the model is  
trained on past behaviour and evaluated on genuinely unseen future transactions.

**Split ratios:** 70% Train · 15% Validation · 15% Test (by row count after deduplication).

> **Note — Bug in Cell 17 (M1):** `keep=false` should be `keep=False` (Python boolean).  
> The duplicate-removal block will raise a `NameError` unless corrected. Please ask M1 to fix it.  
> The cells below assume `df` has already had duplicates removed correctly.

In [ ]:
import pandas as pd

# ── Step 1: Sort entire cleaned dataset chronologically ──
df_sorted = df.sort_values('Time').reset_index(drop=True)

# ── Step 2: Compute split boundaries ──
n       = len(df_sorted)
n_train = int(0.70 * n)
n_val   = int(0.15 * n)
# n_test  = remainder (latest 15%)

df_train = df_sorted.iloc[:n_train].copy()
df_val   = df_sorted.iloc[n_train : n_train + n_val].copy()
df_test  = df_sorted.iloc[n_train + n_val :].copy()

# ── Step 3: Per-split base-rate summary table ──
def split_summary(name, frame):
    total      = len(frame)
    fraud      = frame['Class'].sum()
    legit      = total - fraud
    fraud_pct  = 100 * fraud / total
    legit_pct  = 100 * legit / total
    return {
        'Split'       : name,
        'Total Rows'  : total,
        'Legit (0)'   : legit,
        'Fraud (1)'   : fraud,
        'Legit %'     : f'{legit_pct:.4f}%',
        'Fraud % (base rate)': f'{fraud_pct:.4f}%',
    }

summary_df = pd.DataFrame([
    split_summary('Train (70%)',      df_train),
    split_summary('Validation (15%)', df_val),
    split_summary('Test (15%)',       df_test),
    split_summary('Full Dataset',     df_sorted),
])
display(summary_df)

print(f"\nTime range — Train : {df_train['Time'].min():.0f}s → {df_train['Time'].max():.0f}s")
print(f"Time range — Val   : {df_val['Time'].min():.0f}s   → {df_val['Time'].max():.0f}s")
print(f"Time range — Test  : {df_test['Time'].min():.0f}s  → {df_test['Time'].max():.0f}s")
print("\n✅ Chronological split complete. No overlap between splits.")

---
### 4. Feature Engineering & Preprocessing

**Owner:** Member 2

This section covers:
1. `Amount` outlier inspection — understand the raw distribution before transforming
2. `Amount_log = log1p(Amount)` — compress right skew
3. Scaler comparison — `StandardScaler` vs `RobustScaler` (fitted only on legitimate training rows)
4. Final feature matrix construction — `X_train`, `X_val`, `X_test` passed to M3/M4/M5
5. Scaler saved to disk with `joblib` for full reproducibility
6. Data-leakage prevention checklist

In [ ]:
# ── 4.1  Amount Outlier Inspection ──────────────────────────────────────────
# Inspect the raw Amount distribution before any transformation.
# This informs both the choice of log-transform and the scaler selection.

import numpy as np

print("=" * 55)
print("Raw Amount — percentile breakdown (training split only)")
print("=" * 55)
pct_labels = [0, 1, 5, 25, 50, 75, 95, 99, 100]
amount_pcts = np.percentile(df_train['Amount'], pct_labels)
for p, v in zip(pct_labels, amount_pcts):
    print(f"  p{p:>3d}: ${v:>10.2f}")

# Count extreme outliers (> $2,000) in each split
threshold_extreme = 2000
for name, frame in [('Train', df_train), ('Val', df_val), ('Test', df_test)]:
    n_extreme = (frame['Amount'] > threshold_extreme).sum()
    pct_ext   = 100 * n_extreme / len(frame)
    print(f"\n{name}: {n_extreme} rows with Amount > ${threshold_extreme} ({pct_ext:.3f}%)")

print("\n📌 Insight: Amount is heavily right-skewed with a long tail.")
print("   This motivates log1p() before scaling, and RobustScaler over StandardScaler.")

In [ ]:
# ── 4.2  Feature Engineering: Amount_log = log1p(Amount) ────────────────────
# log1p(x) = log(1 + x) — handles Amount=0 safely (log(1)=0, no -inf)
# Applied identically to all three splits.

import matplotlib.pyplot as plt
import seaborn as sns

for frame in [df_train, df_val, df_test]:
    frame['Amount_log'] = np.log1p(frame['Amount'])

# ── Before / after comparison plot (training split) ──
fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle('Amount Distribution — Before and After log1p Transform (Training Split)',
             fontsize=13, fontweight='bold')

sns.histplot(df_train['Amount'],     bins=80, kde=True, ax=axes[0],
             color='steelblue', edgecolor='white', linewidth=0.3)
axes[0].set_title('Raw Amount (right-skewed)')
axes[0].set_xlabel('Amount ($)')
axes[0].set_ylabel('Count')
axes[0].annotate(
    f"Skewness: {df_train['Amount'].skew():.2f}",
    xy=(0.65, 0.88), xycoords='axes fraction', fontsize=10,
    bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow')
)

sns.histplot(df_train['Amount_log'], bins=80, kde=True, ax=axes[1],
             color='darkorange', edgecolor='white', linewidth=0.3)
axes[1].set_title('Amount_log = log1p(Amount) — compressed tail')
axes[1].set_xlabel('log1p(Amount)')
axes[1].set_ylabel('Count')
axes[1].annotate(
    f"Skewness: {df_train['Amount_log'].skew():.2f}",
    xy=(0.65, 0.88), xycoords='axes fraction', fontsize=10,
    bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow')
)

plt.tight_layout()
plt.savefig('results/figures/amount_log_transform.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Amount_log created in df_train, df_val, df_test. Plot saved to results/figures/.")

#### Why `log1p(Amount)` and why are `V1`–`V28` left untouched?

**`Amount_log = log1p(Amount)`**  
`Amount` is heavily right-skewed: the median is ~\$22, yet some values exceed \$25,000.  
Such a long tail causes two problems:
- **StandardScaler** becomes sensitive to these outliers (mean and std are pulled high),
  producing poor standardisation for the majority of transactions.
- **GMM covariance estimation** can be distorted if one feature has a far larger raw range
  than all others.

`log1p(x) = log(1 + x)` safely handles `Amount = 0` (giving 0), compresses the long tail,
and brings the distribution much closer to symmetric — reducing the skewness from ~17 to ~0.5.

**`V1`–`V28` are kept as-is**  
These 28 features are the output of PCA applied to the original transaction features
(details hidden for privacy by the dataset authors). PCA produces components that are:
- Already **zero-centred** (mean ≈ 0)
- Already **orthogonal** (uncorrelated by construction)
- Scaled so that the first components carry the most variance

Re-scaling or transforming them would distort the principal-component geometry and
destroy the interpretability of the feature space without adding information.

**`Time` is excluded from features**  
`Time` was used only to enforce the chronological split ordering. As a raw elapsed-seconds
value it has no per-transaction discriminative meaning once the split is done.
Hour-of-day (`(Time // 3600) % 24`) is an optional engineered feature deferred to
Member 4's ablation experiments (Section 10).

In [ ]:
# ── 4.3  Feature Column Contract ────────────────────────────────────────────
# 29 features: V1–V28 (PCA components, untouched) + Amount_log (engineered)
# This list is the single source of truth used by M3, M4, and M5.

V_COLS       = [f'V{i}' for i in range(1, 29)]          # V1 … V28
FEATURE_COLS = V_COLS + ['Amount_log']                   # 29 features total

print(f"Feature count : {len(FEATURE_COLS)}")
print(f"Features      : {FEATURE_COLS}")

# Sanity check — all columns present in each split
for name, frame in [('df_train', df_train), ('df_val', df_val), ('df_test', df_test)]:
    missing = [c for c in FEATURE_COLS if c not in frame.columns]
    if missing:
        print(f"❌ {name} missing columns: {missing}")
    else:
        print(f"✅ {name}: all {len(FEATURE_COLS)} feature columns present")

In [ ]:
# ── 4.4  Scaler Comparison: StandardScaler vs RobustScaler ──────────────────
# Golden rule: fit the scaler ONLY on legitimate (Class == 0) training rows.
# Fraud rows never enter the fit — they are the anomaly the model must detect.
# The same fitted scaler is then .transform()-ed on val and test (never re-fitted).

from sklearn.preprocessing import StandardScaler, RobustScaler

# Legitimate training rows only (used for fitting)
legit_train_mask = df_train['Class'] == 0
legit_train_X    = df_train.loc[legit_train_mask, FEATURE_COLS]

print(f"Rows used for scaler fit (legit-train only): {len(legit_train_X):,}")
print(f"  (excluded fraud rows from fit            : {legit_train_mask.sum():,} legit  /"
      f" {(~legit_train_mask).sum()} fraud)")

# ── Fit both scalers on legit-train ──
std_scaler = StandardScaler().fit(legit_train_X)
rob_scaler = RobustScaler().fit(legit_train_X)

# ── Apply to training set (full, including fraud rows — for comparison) ──
X_train_std = std_scaler.transform(df_train[FEATURE_COLS])
X_train_rob = rob_scaler.transform(df_train[FEATURE_COLS])

# ── Comparison table: mean & std after scaling (legit rows, 5 representative features) ──
import pandas as pd
rep_features = ['V1', 'V4', 'V14', 'V17', 'Amount_log']
rep_idx      = [FEATURE_COLS.index(c) for c in rep_features]

legit_mask_arr = (df_train['Class'] == 0).values

rows = []
for feat, idx in zip(rep_features, rep_idx):
    rows.append({
        'Feature'               : feat,
        'Raw mean (legit-train)': df_train.loc[legit_train_mask, feat].mean(),
        'Raw std  (legit-train)': df_train.loc[legit_train_mask, feat].std(),
        'Std mean (legit rows)' : X_train_std[legit_mask_arr, idx].mean(),
        'Std std  (legit rows)' : X_train_std[legit_mask_arr, idx].std(),
        'Rob mean (legit rows)' : X_train_rob[legit_mask_arr, idx].mean(),
        'Rob std  (legit rows)' : X_train_rob[legit_mask_arr, idx].std(),
    })

cmp_df = pd.DataFrame(rows).set_index('Feature').round(4)
print("\n── Scaler comparison on 5 representative features (legit training rows) ──")
display(cmp_df)

# ── Visualise Amount_log scaling: both scalers ──
import matplotlib.pyplot as plt
import seaborn as sns

amt_idx = FEATURE_COLS.index('Amount_log')
fig, axes = plt.subplots(1, 3, figsize=(18, 4))
fig.suptitle('Amount_log Scaling Comparison (Training Split, All Rows)',
             fontsize=12, fontweight='bold')

for ax, data, title in zip(
    axes,
    [df_train['Amount_log'].values,
     X_train_std[:, amt_idx],
     X_train_rob[:, amt_idx]],
    ['Unscaled Amount_log', 'StandardScaler', 'RobustScaler']
):
    sns.histplot(data, bins=80, kde=True, ax=ax, color='mediumslateblue',
                 edgecolor='white', linewidth=0.3)
    ax.set_title(title)
    ax.set_xlabel('Value')
    ax.set_ylabel('Count')
    ax.annotate(f"mean={data.mean():.2f}\nstd={data.std():.2f}",
                xy=(0.02, 0.88), xycoords='axes fraction', fontsize=9,
                bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow'))

plt.tight_layout()
plt.savefig('results/figures/scaler_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n✅ Scaler comparison complete. Plot saved to results/figures/.")

#### Scaler Decision: **RobustScaler chosen**

| Criterion | StandardScaler | RobustScaler | Winner |
|---|---|---|---|
| Centring statistic | Mean | Median | RobustScaler (median is outlier-resistant) |
| Scale statistic | Std deviation | IQR (Q3 − Q1) | RobustScaler (IQR ignores tail) |
| Sensitivity to extreme Amount values | High — mean/std pulled by outliers | Low — median/IQR unaffected | RobustScaler |
| Sensitivity to fraud outliers in val/test | Potentially affected | Unaffected (fitted on legit-train only in both cases) | Tie |
| Works well for GMM in 30-D? | Yes, if distribution is near-Gaussian | Yes, and more stable with heavy-tailed features | RobustScaler |

**Conclusion:** `RobustScaler` is the final choice.  
Although `Amount_log` reduces skewness, the tail of legitimate high-value transactions  
still makes the IQR-based scaling more stable than the std-based one.  
`StandardScaler` is retained as a baseline in **Member 4's ablation (Section 10)** —  
both scalers have already been fitted and saved so the experiment requires no refitting.

In [ ]:
# ── 4.5  Final Scaler Application + Feature Matrix Construction ─────────────
# Choose RobustScaler as the production scaler.
# Apply identically (transform only) to train, val, and test.
# Never call .fit() or .fit_transform() on val or test — that would leak statistics.

import joblib, os

final_scaler = rob_scaler          # already fitted on legit_train_X above

# ── Feature matrices (numpy arrays passed to M3 / M4 / M5) ──
X_train = final_scaler.transform(df_train[FEATURE_COLS])   # shape (n_train, 29)
X_val   = final_scaler.transform(df_val[FEATURE_COLS])     # shape (n_val,   29)
X_test  = final_scaler.transform(df_test[FEATURE_COLS])    # shape (n_test,  29)

# ── Label vectors (for M5 evaluation; never used in GMM training) ──
y_train = df_train['Class'].values
y_val   = df_val['Class'].values
y_test  = df_test['Class'].values

# ── Sanity assertions ──
assert X_train.shape[1] == len(FEATURE_COLS), "Wrong feature count in X_train"
assert X_val.shape[1]   == len(FEATURE_COLS), "Wrong feature count in X_val"
assert X_test.shape[1]  == len(FEATURE_COLS), "Wrong feature count in X_test"
assert not np.isnan(X_train).any(), "NaN found in X_train"
assert not np.isnan(X_val).any(),   "NaN found in X_val"
assert not np.isnan(X_test).any(),  "NaN found in X_test"

print("── Final feature matrices ──")
print(f"  X_train : {X_train.shape}  |  y_train fraud count: {y_train.sum()}")
print(f"  X_val   : {X_val.shape}    |  y_val   fraud count: {y_val.sum()}")
print(f"  X_test  : {X_test.shape}   |  y_test  fraud count: {y_test.sum()}")

# ── Save scaler to disk ──
SCALER_PATH = os.path.join('results', 'scaler_robust.joblib')
os.makedirs('results', exist_ok=True)
joblib.dump(final_scaler, SCALER_PATH)
print(f"\n✅ Final scaler saved → {SCALER_PATH}")
print("   To reload: scaler = joblib.load('results/scaler_robust.joblib')")
print("\n✅ All assertions passed. X_train / X_val / X_test are ready for M3.")

---
### ✅ Data-Leakage Prevention Checklist

| # | Check | Status | How it is enforced in this notebook |
|---|---|---|---|
| 1 | Scaler fitted **only on legitimate training rows** | ✅ | `legit_train_X = df_train[df_train['Class']==0][FEATURE_COLS]` — fraud rows excluded from `.fit()` |
| 2 | Scaler **applied but never re-fitted** on val & test | ✅ | Only `.transform()` called on `df_val` and `df_test`; `.fit()` called once on `legit_train_X` |
| 3 | Fraud rows **excluded from GMM training** | ✅ | M3 will train on `X_train[y_train == 0]` — label vector `y_train` provided for this filter |
| 4 | **No future information** in the training split | ✅ | Dataset sorted by `Time` before splitting; `df_train` contains only the earliest 70% of transactions |
| 5 | **Threshold selected on validation only** | ✅ | `X_val` / `y_val` passed to M5 for threshold tuning; `X_test` kept separate |
| 6 | **Test set untouched** until final evaluation | ✅ | `X_test` / `y_test` handed to M5 and run once; no decisions or tuning made on test scores |
| 7 | `Amount_log` computed **before** the scaler is fitted | ✅ | Cell 31 adds `Amount_log` to `df_train/val/test`; Cell 36 scales; no look-ahead into val/test |
| 8 | **No feature derived from the label** (`Class`) | ✅ | `Class` appears only in `y_train/val/test`; never in `FEATURE_COLS` |

---
**Handoff to downstream members:**

| Variable | Shape | Consumer |
|---|---|---|
| `X_train` | `ndarray (n_train, 29)` | **M3** — fit GMM on `X_train[y_train==0]` |
| `X_val` | `ndarray (n_val, 29)` | **M3** scoring · **M5** threshold selection |
| `X_test` | `ndarray (n_test, 29)` | **M5** final evaluation (use once) |
| `y_train` | `ndarray (n_train,)` | **M3** legit-row filter |
| `y_val` | `ndarray (n_val,)` | **M5** threshold tuning |
| `y_test` | `ndarray (n_test,)` | **M5** final evaluation |
| `FEATURE_COLS` | `list` of 29 strings | **M3 / M4** reference |
| `final_scaler` | `RobustScaler` object | **M4** ablation (swap with `std_scaler`) |
| `SCALER_PATH` | `str` | **M1** reproducibility section (§12) |