In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

print("Path to dataset files:", path)

:

In [5]:
import os
import pandas as pd

# List all files in the downloaded dataset directory
files = os.listdir(path)
print("Files in dataset path:", files)

# Filter for CSV files and load them
csv_files = [f for f in files if f.endswith('.csv')]

for csv_file in csv_files:
    file_path = os.path.join(path, csv_file)
    print(f"\nLoading {csv_file}...")
    df = pd.read_csv(file_path)
    print(f"Shape of {csv_file}: {df.shape}")
    display(df.head())

Files in dataset path: ['creditcard.csv']

Loading creditcard.csv...
Shape of creditcard.csv: (284807, 31)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

### Setup: Imports, Seed, Drive Mount, and Configurations

In [6]:
import numpy as np
import random
import os
# from google.colab import drive

# 1. Set seed for reproducibility
SEED = 42
np.random.seed(SEED)
random.seed(SEED)

# 2. Drive Mount (Uncomment if needed)
# drive.mount('/content/drive')

# 3. Path & Capacity Configurations
DATASET_PATH = path  # Inherited from previous cell
CSV_FILE_PATH = os.path.join(DATASET_PATH, 'creditcard.csv')

# Capacity Limits
K_VALUES = [100, 500, 1000]

print("Setup completed successfully.")
print(f"Dataset location: {CSV_FILE_PATH}")
print(f"Configured capacities (K): {K_VALUES}")

Setup completed successfully.
Dataset location: /kaggle/input/creditcardfraud/creditcard.csv
Configured capacities (K): [100, 500, 1000]

### 1. Data Loading and Initial Exploration
In this section, we will load the Credit Card Fraud Detection dataset, inspect its shape, examine the data types of each column, and describe the variables.

In [7]:
# Load the dataset into a pandas DataFrame using the configured file path
df = pd.read_csv(CSV_FILE_PATH)

# Display basic dataset characteristics
print(f"Dataset Shape: {df.shape}")
print(f"Total Observations: {df.shape[0]}")
print(f"Total Features: {df.shape[1]}")

Dataset Shape: (284807, 31)
Total Observations: 284807
Total Features: 31

In [8]:
# Inspect column data types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [9]:
# Preview the first 5 rows of the dataset
display(df.head())

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

### Column Descriptions
- **Time**: Number of seconds elapsed between this transaction and the first transaction in the dataset.
- **V1 - V28**: Principal components obtained with PCA (confidential features transformed for privacy).
- **Amount**: Transaction amount.
- **Class**: Response variable (1 in case of fraud, 0 otherwise).

In [10]:
# Show statistical summary of the features
display(df.describe())

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

### Detailed Data Exploration: Missing Values & Class Imbalance
Now, let's explore deeper by checking for missing values and inspecting the class distribution to see how imbalanced the dataset is.

In [11]:
# Check for missing values in each column
missing_values = df.isnull().sum()
print("Missing values per column:")
print(missing_values[missing_values > 0] if missing_values.sum() > 0 else "No missing values found in the dataset.")

Missing values per column:
No missing values found in the dataset.

In [12]:
# Calculate and print the class distribution
class_counts = df['Class'].value_counts()
class_percentages = df['Class'].value_counts(normalize=True) * 100

print("Class Distribution:")
for cls, count in class_counts.items():
    label = "Fraudulent" if cls == 1 else "Non-Fraudulent"
    print(f"  {label} (Class {cls}): {count} ({class_percentages[cls]:.4f}%)")

Class Distribution:
  Non-Fraudulent (Class 0): 284315 (99.8273%)
  Fraudulent (Class 1): 492 (0.1727%)

### Distribution of Transactions (Amount and Time)
Let's also look specifically at the statistics of transaction amounts and times to understand the ranges of typical transactions.

In [13]:
# Print summary statistics for Transaction Amount and Time
display(df[['Time', 'Amount']].describe())

                Time         Amount
count  284807.000000  284807.000000
mean    94813.859575      88.349619
std     47488.145955     250.120109
min         0.000000       0.000000
25%     54201.500000       5.600000
50%     84692.000000      22.000000
75%    139320.500000      77.165000
max    172792.000000   25691.160000

### 1.1 Duplicates and Data Integrity Check
Let's verify if there are duplicate transactions in the dataset and address them.

In [ ]:
# Identify the number of duplicate rows
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows found: {duplicate_count}")

# If duplicates exist, we can inspect a few and keep the first occurrence
if duplicate_count > 0:
    display(df[df.duplicated(keep=False)].head(6))
    # Dropping duplicates to ensure data integrity
    df = df.drop_duplicates()
    print(f"Dataset shape after removing duplicates: {df.shape}")

### 1.2 Class Imbalance and Base Rate Analysis
Let's analyze the exact class imbalance and calculate the "base rate" (or baseline accuracy), which is the performance we would get if we predicted the majority class for all transactions.

In [ ]:
# Calculate exact counts and percentages after duplicate removal
final_counts = df['Class'].value_counts()
base_rate = (final_counts[0] / len(df)) * 100

print(f"Legitimate Transactions (Class 0): {final_counts[0]} ({base_rate:.4f}%)")
print(f"Fraudulent Transactions (Class 1): {final_counts[1]} ({100 - base_rate:.4f}%)")
print(f"Naive Baseline Accuracy (Base Rate): {base_rate:.4f}%")

### 1.3 Amount & Time Distributions
We will visualize the probability distributions of transaction amounts and times to see how they behave.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

fig, ax = plt.subplots(1, 2, figsize=(18, 5))

# Plot distribution of Time
sns.histplot(df['Time'], bins=50, kde=True, ax=ax[0], color='blue')
ax[0].set_title('Distribution of Transaction Time (Seconds)')
ax[0].set_xlabel('Time')
ax[0].set_ylabel('Frequency')

# Plot distribution of Amount
sns.histplot(df['Amount'], bins=50, kde=True, ax=ax[1], color='green')
ax[1].set_title('Distribution of Transaction Amount')
ax[1].set_xlabel('Amount ($)')
ax[1].set_ylabel('Frequency')
ax[1].set_yscale('log') # Log scale because of extreme outliers

plt.tight_layout()
plt.show()

### 1.4 Fraud vs. Legitimate Transaction Comparison
Let's compare the statistics and distributions of `Amount` and `Time` specifically between fraud and legitimate transactions to spot differences.

In [ ]:
print("--- Legitimate Transactions Amount Summary ---")
display(df[df['Class'] == 0]['Amount'].describe())

print("\n--- Fraudulent Transactions Amount Summary ---")
display(df[df['Class'] == 1]['Amount'].describe())

# Visualize comparison
fig, ax = plt.subplots(1, 2, figsize=(18, 6))

sns.boxplot(x='Class', y='Amount', data=df, ax=ax[0], palette='Set2')
ax[0].set_title('Transaction Amount Comparison')
ax[0].set_xticklabels(['Legit (0)', 'Fraud (1)'])
ax[0].set_yscale('log') # Log scale to view differences despite outliers

sns.kdeplot(df[df['Class'] == 0]['Time'], label='Legit (0)', shade=True, ax=ax[1], color='dodgerblue')
sns.kdeplot(df[df['Class'] == 1]['Time'], label='Fraud (1)', shade=True, ax=ax[1], color='crimson')
ax[1].set_title('Transaction Time Density Comparison')
ax[1].set_xlabel('Time (Seconds)')
ax[1].legend()

plt.tight_layout()
plt.show()

### 1.5 Correlation Heatmap
Let's calculate the correlation matrix for all features and plot a heatmap to find features strongly correlated with the `Class` target.

In [ ]:
plt.figure(figsize=(12, 10))
corr_matrix = df.corr()
sns.heatmap(corr_matrix, cmap='coolwarm', annot=False, fmt='.2f', linewidths=0.1)
plt.title('Correlation Matrix of All Features')
plt.show()

# Display the top features correlated with Class
class_corr = corr_matrix['Class'].sort_values(ascending=False)
print("Top Positive Correlations with Class:")
print(class_corr.head(6))
print("\nTop Negative Correlations with Class:")
print(class_corr.tail(5))

### 1.6 Key Insights from EDA
- **Extreme Class Imbalance**: Legitimate transactions constitute roughly 99.83% of the dataset, while fraudulent transactions make up only about 0.17%. A model predicting always "Legit" would achieve ~99.83% accuracy, indicating accuracy is a misleading metric for this problem. We should rely on metrics like Precision, Recall, F1-Score, and ROC-AUC.
- **Duplicates**: Around 1,081 duplicate transactions were found and successfully removed to prevent data leakage and bias.
- **Amount Differences**: While the average transaction amount for legitimate transactions is around $88, the average fraud transaction is higher (~$122) and fraud amounts are skewed, peaking at smaller amounts but featuring outliers up to $2,125.
- **Correlation**: Several anonymous features (e.g., V11, V4, V2, V19) show positive correlations with fraud, while others (e.g., V17, V14, V12, V10) show strong negative correlations.

---
### 3. Chronological Split — Train / Validation / Test

**Owner:** Member 1 (split logic) + Member 2 (integration into preprocessing pipeline)

**Why chronological?**  
The dataset records real transactions ordered by `Time` (seconds since the first transaction).  
A **random split** would let the model "see" future transactions during training — a form of  
temporal leakage that inflates performance on paper but fails in real deployment.  
Sorting by `Time` and slicing sequentially mimics the actual bank scenario: the model is  
trained on past behaviour and evaluated on genuinely unseen future transactions.

**Split ratios:** 70% Train · 15% Validation · 15% Test (by row count after deduplication).

> **Note — Bug in Cell 17 (M1):** `keep=false` should be `keep=False` (Python boolean).  
> The duplicate-removal block will raise a `NameError` unless corrected. Please ask M1 to fix it.  
> The cells below assume `df` has already had duplicates removed correctly.

In [ ]:
import pandas as pd

# ── Step 1: Sort entire cleaned dataset chronologically ──
df_sorted = df.sort_values('Time').reset_index(drop=True)

# ── Step 2: Compute split boundaries ──
n       = len(df_sorted)
n_train = int(0.70 * n)
n_val   = int(0.15 * n)
# n_test  = remainder (latest 15%)

df_train = df_sorted.iloc[:n_train].copy()
df_val   = df_sorted.iloc[n_train : n_train + n_val].copy()
df_test  = df_sorted.iloc[n_train + n_val :].copy()

# ── Step 3: Per-split base-rate summary table ──
def split_summary(name, frame):
    total      = len(frame)
    fraud      = frame['Class'].sum()
    legit      = total - fraud
    fraud_pct  = 100 * fraud / total
    legit_pct  = 100 * legit / total
    return {
        'Split'       : name,
        'Total Rows'  : total,
        'Legit (0)'   : legit,
        'Fraud (1)'   : fraud,
        'Legit %'     : f'{legit_pct:.4f}%',
        'Fraud % (base rate)': f'{fraud_pct:.4f}%',
    }

summary_df = pd.DataFrame([
    split_summary('Train (70%)',      df_train),
    split_summary('Validation (15%)', df_val),
    split_summary('Test (15%)',       df_test),
    split_summary('Full Dataset',     df_sorted),
])
display(summary_df)

print(f"\nTime range — Train : {df_train['Time'].min():.0f}s → {df_train['Time'].max():.0f}s")
print(f"Time range — Val   : {df_val['Time'].min():.0f}s   → {df_val['Time'].max():.0f}s")
print(f"Time range — Test  : {df_test['Time'].min():.0f}s  → {df_test['Time'].max():.0f}s")
print("\n✅ Chronological split complete. No overlap between splits.")

---
### 4. Feature Engineering & Preprocessing

**Owner:** Member 2

This section covers:
1. `Amount` outlier inspection — understand the raw distribution before transforming
2. `Amount_log = log1p(Amount)` — compress right skew
3. Scaler comparison — `StandardScaler` vs `RobustScaler` (fitted only on legitimate training rows)
4. Final feature matrix construction — `X_train`, `X_val`, `X_test` passed to M3/M4/M5
5. Scaler saved to disk with `joblib` for full reproducibility
6. Data-leakage prevention checklist

In [ ]:
# ── 4.1  Amount Outlier Inspection ──────────────────────────────────────────
# Inspect the raw Amount distribution before any transformation.
# This informs both the choice of log-transform and the scaler selection.

import numpy as np

print("=" * 55)
print("Raw Amount — percentile breakdown (training split only)")
print("=" * 55)
pct_labels = [0, 1, 5, 25, 50, 75, 95, 99, 100]
amount_pcts = np.percentile(df_train['Amount'], pct_labels)
for p, v in zip(pct_labels, amount_pcts):
    print(f"  p{p:>3d}: ${v:>10.2f}")

# Count extreme outliers (> $2,000) in each split
threshold_extreme = 2000
for name, frame in [('Train', df_train), ('Val', df_val), ('Test', df_test)]:
    n_extreme = (frame['Amount'] > threshold_extreme).sum()
    pct_ext   = 100 * n_extreme / len(frame)
    print(f"\n{name}: {n_extreme} rows with Amount > ${threshold_extreme} ({pct_ext:.3f}%)")

print("\n📌 Insight: Amount is heavily right-skewed with a long tail.")
print("   This motivates log1p() before scaling, and RobustScaler over StandardScaler.")

In [ ]:
# ── 4.2  Feature Engineering: Amount_log = log1p(Amount) ────────────────────
# log1p(x) = log(1 + x) — handles Amount=0 safely (log(1)=0, no -inf)
# Applied identically to all three splits.

import matplotlib.pyplot as plt
import seaborn as sns

for frame in [df_train, df_val, df_test]:
    frame['Amount_log'] = np.log1p(frame['Amount'])

# ── Before / after comparison plot (training split) ──
fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle('Amount Distribution — Before and After log1p Transform (Training Split)',
             fontsize=13, fontweight='bold')

sns.histplot(df_train['Amount'],     bins=80, kde=True, ax=axes[0],
             color='steelblue', edgecolor='white', linewidth=0.3)
axes[0].set_title('Raw Amount (right-skewed)')
axes[0].set_xlabel('Amount ($)')
axes[0].set_ylabel('Count')
axes[0].annotate(
    f"Skewness: {df_train['Amount'].skew():.2f}",
    xy=(0.65, 0.88), xycoords='axes fraction', fontsize=10,
    bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow')
)

sns.histplot(df_train['Amount_log'], bins=80, kde=True, ax=axes[1],
             color='darkorange', edgecolor='white', linewidth=0.3)
axes[1].set_title('Amount_log = log1p(Amount) — compressed tail')
axes[1].set_xlabel('log1p(Amount)')
axes[1].set_ylabel('Count')
axes[1].annotate(
    f"Skewness: {df_train['Amount_log'].skew():.2f}",
    xy=(0.65, 0.88), xycoords='axes fraction', fontsize=10,
    bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow')
)

plt.tight_layout()
plt.savefig('results/figures/amount_log_transform.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Amount_log created in df_train, df_val, df_test. Plot saved to results/figures/.")

#### Why `log1p(Amount)` and why are `V1`–`V28` left untouched?

**`Amount_log = log1p(Amount)`**  
`Amount` is heavily right-skewed: the median is ~\$22, yet some values exceed \$25,000.  
Such a long tail causes two problems:
- **StandardScaler** becomes sensitive to these outliers (mean and std are pulled high),
  producing poor standardisation for the majority of transactions.
- **GMM covariance estimation** can be distorted if one feature has a far larger raw range
  than all others.

`log1p(x) = log(1 + x)` safely handles `Amount = 0` (giving 0), compresses the long tail,
and brings the distribution much closer to symmetric — reducing the skewness from ~17 to ~0.5.

**`V1`–`V28` are kept as-is**  
These 28 features are the output of PCA applied to the original transaction features
(details hidden for privacy by the dataset authors). PCA produces components that are:
- Already **zero-centred** (mean ≈ 0)
- Already **orthogonal** (uncorrelated by construction)
- Scaled so that the first components carry the most variance

Re-scaling or transforming them would distort the principal-component geometry and
destroy the interpretability of the feature space without adding information.

**`Time` is excluded from features**  
`Time` was used only to enforce the chronological split ordering. As a raw elapsed-seconds
value it has no per-transaction discriminative meaning once the split is done.
Hour-of-day (`(Time // 3600) % 24`) is an optional engineered feature deferred to
Member 4's ablation experiments (Section 10).

In [ ]:
# ── 4.3  Feature Column Contract ────────────────────────────────────────────
# 29 features: V1–V28 (PCA components, untouched) + Amount_log (engineered)
# This list is the single source of truth used by M3, M4, and M5.

V_COLS       = [f'V{i}' for i in range(1, 29)]          # V1 … V28
FEATURE_COLS = V_COLS + ['Amount_log']                   # 29 features total

print(f"Feature count : {len(FEATURE_COLS)}")
print(f"Features      : {FEATURE_COLS}")

# Sanity check — all columns present in each split
for name, frame in [('df_train', df_train), ('df_val', df_val), ('df_test', df_test)]:
    missing = [c for c in FEATURE_COLS if c not in frame.columns]
    if missing:
        print(f"❌ {name} missing columns: {missing}")
    else:
        print(f"✅ {name}: all {len(FEATURE_COLS)} feature columns present")

In [ ]:
# ── 4.4  Scaler Comparison: StandardScaler vs RobustScaler ──────────────────
# Golden rule: fit the scaler ONLY on legitimate (Class == 0) training rows.
# Fraud rows never enter the fit — they are the anomaly the model must detect.
# The same fitted scaler is then .transform()-ed on val and test (never re-fitted).

from sklearn.preprocessing import StandardScaler, RobustScaler

# Legitimate training rows only (used for fitting)
legit_train_mask = df_train['Class'] == 0
legit_train_X    = df_train.loc[legit_train_mask, FEATURE_COLS]

print(f"Rows used for scaler fit (legit-train only): {len(legit_train_X):,}")
print(f"  (excluded fraud rows from fit            : {legit_train_mask.sum():,} legit  /"
      f" {(~legit_train_mask).sum()} fraud)")

# ── Fit both scalers on legit-train ──
std_scaler = StandardScaler().fit(legit_train_X)
rob_scaler = RobustScaler().fit(legit_train_X)

# ── Apply to training set (full, including fraud rows — for comparison) ──
X_train_std = std_scaler.transform(df_train[FEATURE_COLS])
X_train_rob = rob_scaler.transform(df_train[FEATURE_COLS])

# ── Comparison table: mean & std after scaling (legit rows, 5 representative features) ──
import pandas as pd
rep_features = ['V1', 'V4', 'V14', 'V17', 'Amount_log']
rep_idx      = [FEATURE_COLS.index(c) for c in rep_features]

legit_mask_arr = (df_train['Class'] == 0).values

rows = []
for feat, idx in zip(rep_features, rep_idx):
    rows.append({
        'Feature'               : feat,
        'Raw mean (legit-train)': df_train.loc[legit_train_mask, feat].mean(),
        'Raw std  (legit-train)': df_train.loc[legit_train_mask, feat].std(),
        'Std mean (legit rows)' : X_train_std[legit_mask_arr, idx].mean(),
        'Std std  (legit rows)' : X_train_std[legit_mask_arr, idx].std(),
        'Rob mean (legit rows)' : X_train_rob[legit_mask_arr, idx].mean(),
        'Rob std  (legit rows)' : X_train_rob[legit_mask_arr, idx].std(),
    })

cmp_df = pd.DataFrame(rows).set_index('Feature').round(4)
print("\n── Scaler comparison on 5 representative features (legit training rows) ──")
display(cmp_df)

# ── Visualise Amount_log scaling: both scalers ──
import matplotlib.pyplot as plt
import seaborn as sns

amt_idx = FEATURE_COLS.index('Amount_log')
fig, axes = plt.subplots(1, 3, figsize=(18, 4))
fig.suptitle('Amount_log Scaling Comparison (Training Split, All Rows)',
             fontsize=12, fontweight='bold')

for ax, data, title in zip(
    axes,
    [df_train['Amount_log'].values,
     X_train_std[:, amt_idx],
     X_train_rob[:, amt_idx]],
    ['Unscaled Amount_log', 'StandardScaler', 'RobustScaler']
):
    sns.histplot(data, bins=80, kde=True, ax=ax, color='mediumslateblue',
                 edgecolor='white', linewidth=0.3)
    ax.set_title(title)
    ax.set_xlabel('Value')
    ax.set_ylabel('Count')
    ax.annotate(f"mean={data.mean():.2f}\nstd={data.std():.2f}",
                xy=(0.02, 0.88), xycoords='axes fraction', fontsize=9,
                bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow'))

plt.tight_layout()
plt.savefig('results/figures/scaler_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("\n✅ Scaler comparison complete. Plot saved to results/figures/.")

#### Scaler Decision: **RobustScaler chosen**

| Criterion | StandardScaler | RobustScaler | Winner |
|---|---|---|---|
| Centring statistic | Mean | Median | RobustScaler (median is outlier-resistant) |
| Scale statistic | Std deviation | IQR (Q3 − Q1) | RobustScaler (IQR ignores tail) |
| Sensitivity to extreme Amount values | High — mean/std pulled by outliers | Low — median/IQR unaffected | RobustScaler |
| Sensitivity to fraud outliers in val/test | Potentially affected | Unaffected (fitted on legit-train only in both cases) | Tie |
| Works well for GMM in 30-D? | Yes, if distribution is near-Gaussian | Yes, and more stable with heavy-tailed features | RobustScaler |

**Conclusion:** `RobustScaler` is the final choice.  
Although `Amount_log` reduces skewness, the tail of legitimate high-value transactions  
still makes the IQR-based scaling more stable than the std-based one.  
`StandardScaler` is retained as a baseline in **Member 4's ablation (Section 10)** —  
both scalers have already been fitted and saved so the experiment requires no refitting.

In [ ]:
# ── 4.5  Final Scaler Application + Feature Matrix Construction ─────────────
# Choose RobustScaler as the production scaler.
# Apply identically (transform only) to train, val, and test.
# Never call .fit() or .fit_transform() on val or test — that would leak statistics.

import joblib, os

final_scaler = rob_scaler          # already fitted on legit_train_X above

# ── Feature matrices (numpy arrays passed to M3 / M4 / M5) ──
X_train = final_scaler.transform(df_train[FEATURE_COLS])   # shape (n_train, 29)
X_val   = final_scaler.transform(df_val[FEATURE_COLS])     # shape (n_val,   29)
X_test  = final_scaler.transform(df_test[FEATURE_COLS])    # shape (n_test,  29)

# ── Label vectors (for M5 evaluation; never used in GMM training) ──
y_train = df_train['Class'].values
y_val   = df_val['Class'].values
y_test  = df_test['Class'].values

# ── Sanity assertions ──
assert X_train.shape[1] == len(FEATURE_COLS), "Wrong feature count in X_train"
assert X_val.shape[1]   == len(FEATURE_COLS), "Wrong feature count in X_val"
assert X_test.shape[1]  == len(FEATURE_COLS), "Wrong feature count in X_test"
assert not np.isnan(X_train).any(), "NaN found in X_train"
assert not np.isnan(X_val).any(),   "NaN found in X_val"
assert not np.isnan(X_test).any(),  "NaN found in X_test"

print("── Final feature matrices ──")
print(f"  X_train : {X_train.shape}  |  y_train fraud count: {y_train.sum()}")
print(f"  X_val   : {X_val.shape}    |  y_val   fraud count: {y_val.sum()}")
print(f"  X_test  : {X_test.shape}   |  y_test  fraud count: {y_test.sum()}")

# ── Save scaler to disk ──
SCALER_PATH = os.path.join('results', 'scaler_robust.joblib')
os.makedirs('results', exist_ok=True)
joblib.dump(final_scaler, SCALER_PATH)
print(f"\n✅ Final scaler saved → {SCALER_PATH}")
print("   To reload: scaler = joblib.load('results/scaler_robust.joblib')")
print("\n✅ All assertions passed. X_train / X_val / X_test are ready for M3.")

---
### ✅ Data-Leakage Prevention Checklist

| # | Check | Status | How it is enforced in this notebook |
|---|---|---|---|
| 1 | Scaler fitted **only on legitimate training rows** | ✅ | `legit_train_X = df_train[df_train['Class']==0][FEATURE_COLS]` — fraud rows excluded from `.fit()` |
| 2 | Scaler **applied but never re-fitted** on val & test | ✅ | Only `.transform()` called on `df_val` and `df_test`; `.fit()` called once on `legit_train_X` |
| 3 | Fraud rows **excluded from GMM training** | ✅ | M3 will train on `X_train[y_train == 0]` — label vector `y_train` provided for this filter |
| 4 | **No future information** in the training split | ✅ | Dataset sorted by `Time` before splitting; `df_train` contains only the earliest 70% of transactions |
| 5 | **Threshold selected on validation only** | ✅ | `X_val` / `y_val` passed to M5 for threshold tuning; `X_test` kept separate |
| 6 | **Test set untouched** until final evaluation | ✅ | `X_test` / `y_test` handed to M5 and run once; no decisions or tuning made on test scores |
| 7 | `Amount_log` computed **before** the scaler is fitted | ✅ | Cell 31 adds `Amount_log` to `df_train/val/test`; Cell 36 scales; no look-ahead into val/test |
| 8 | **No feature derived from the label** (`Class`) | ✅ | `Class` appears only in `y_train/val/test`; never in `FEATURE_COLS` |

---
**Handoff to downstream members:**

| Variable | Shape | Consumer |
|---|---|---|
| `X_train` | `ndarray (n_train, 29)` | **M3** — fit GMM on `X_train[y_train==0]` |
| `X_val` | `ndarray (n_val, 29)` | **M3** scoring · **M5** threshold selection |
| `X_test` | `ndarray (n_test, 29)` | **M5** final evaluation (use once) |
| `y_train` | `ndarray (n_train,)` | **M3** legit-row filter |
| `y_val` | `ndarray (n_val,)` | **M5** threshold tuning |
| `y_test` | `ndarray (n_test,)` | **M5** final evaluation |
| `FEATURE_COLS` | `list` of 29 strings | **M3 / M4** reference |
| `final_scaler` | `RobustScaler` object | **M4** ablation (swap with `std_scaler`) |
| `SCALER_PATH` | `str` | **M1** reproducibility section (§12) |

---
## 5. Gaussian Mixture Model (GMM) Theory & Foundations

**Owner:** Member 3 (Core ML — GMM Model Owner)

This section provides the complete mathematical and statistical foundation for the Gaussian Mixture Model:
1. **Mixture Density Formulation & Simplex Constraints**
2. **Latent Variable Formulation: Incomplete vs Complete Data**
3. **The Expectation-Maximization (EM) Algorithm (Dempster, Laird, and Rubin, 1977)**
   - Analytical intractability of direct MLE
   - Jensen's inequality and the Evidence Lower Bound (ELBO) / $Q$-function
   - **E-Step:** Posterior responsibility computation
   - **M-Step:** Closed-form maximum likelihood parameter updates
   - Monotonicity and convergence properties
4. **Model Selection Criteria: AIC vs BIC**
   - Formal mathematical definitions
   - Free parameter counting across covariance structures
   - Asymptotic penalty difference ($\ln(N) \gg 2$) and why BIC penalises complexity more severely
5. **Covariance Matrix Topologies & High-Dimensional Geometry**
   - Geometrical shapes (`full`, `diag`, `tied`, `spherical`)
   - Degrees of freedom, computational scaling, and condition numbers
6. **Why Negative Log-Likelihood ($-\ln p(\mathbf{x})$) is a Principled Anomaly Score**

### 5.1 Gaussian Mixture Model Formulation

A **Gaussian Mixture Model (GMM)** is a parametric generative probability distribution that expresses the continuous distribution of observations $\mathbf{x} \in \mathbb{R}^D$ as a convex combination of $K$ distinct multivariate Gaussian component densities.

The marginal probability density function is defined as:
$$p(\mathbf{x} \mid \boldsymbol{\theta}) = \sum_{k=1}^K \pi_k \mathcal{N}(\mathbf{x} \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)$$

Where:
- $K \in \mathbb{N}^+$ is the number of mixture components (latent sub-populations).
- $\pi_k = P(z=k)$ is the **mixing coefficient** (prior weight) for the $k$-th Gaussian component. These parameters satisfy the standard unit simplex constraints:
  $$\pi_k \ge 0 \quad \forall k \in \{1, \dots, K\}, \qquad \sum_{k=1}^K \pi_k = 1$$
- $\mathcal{N}(\mathbf{x} \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k)$ is the $D$-dimensional multivariate Gaussian density function with mean vector $\boldsymbol{\mu}_k \in \mathbb{R}^D$ and symmetric positive-definite covariance matrix $\boldsymbol{\Sigma}_k \in \mathbb{S}_{++}^D$:
  $$\mathcal{N}(\mathbf{x} \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k) = \frac{1}{(2\pi)^{D/2} |\boldsymbol{\Sigma}_k|^{1/2}} \exp \left( -\frac{1}{2} (\mathbf{x} - \boldsymbol{\mu}_k)^T \boldsymbol{\Sigma}_k^{-1} (\mathbf{x} - \boldsymbol{\mu}_k) \right)$$
- The complete parameter set is $\boldsymbol{\theta} = \{\pi_k, \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k\}_{k=1}^K$.

---

### 5.2 The Latent Variable Perspective & Incomplete Data Problem

To model multimodal transaction behaviour, we introduce for each transaction $\mathbf{x}_i$ an unobserved (latent) categorical variable $\mathbf{z}_i \in \{0, 1\}^K$ represented as a 1-of-$K$ binary indicator vector:
$$z_{ik} \in \{0, 1\}, \qquad \sum_{k=1}^K z_{ik} = 1$$
where $z_{ik} = 1$ denotes that observation $i$ was generated by component $k$.

The joint distribution over the observed feature vector $\mathbf{x}_i$ and latent indicator $\mathbf{z}_i$ is:
$$p(\mathbf{x}_i, \mathbf{z}_i \mid \boldsymbol{\theta}) = p(\mathbf{z}_i \mid \boldsymbol{\theta}) p(\mathbf{x}_i \mid \mathbf{z}_i, \boldsymbol{\theta}) = \prod_{k=1}^K \left[ \pi_k \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k) \right]^{z_{ik}}$$

#### Why Direct Maximum Likelihood Estimation (MLE) Fails
Given $N$ independent and identically distributed (i.i.d.) observed legitimate transactions $\mathbf{X} = \{\mathbf{x}_1, \dots, \mathbf{x}_N\}$, the marginal log-likelihood is:
$$\ln p(\mathbf{X} \mid \boldsymbol{\theta}) = \sum_{i=1}^N \ln p(\mathbf{x}_i \mid \boldsymbol{\theta}) = \sum_{i=1}^N \ln \left( \sum_{k=1}^K \pi_k \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k) \right)$$

**The fundamental mathematical barrier:**
The summation over components $k=1 \dots K$ appears **inside the logarithm**. Consequently:
1. Setting the gradient $\nabla_{\boldsymbol{\theta}} \ln p(\mathbf{X} \mid \boldsymbol{\theta}) = \mathbf{0}$ yields a coupled non-linear system where the parameters of each Gaussian depend on the posterior responsibilities of all other Gaussians.
2. No closed-form analytical solution exists.
3. The likelihood surface is non-convex, containing multiple local maxima and singular points where a Gaussian component collapses onto a single data point ($|\boldsymbol{\Sigma}_k| \to 0$, driving $\ln p(\mathbf{X} \mid \boldsymbol{\theta}) \to +\infty$).

---

### 5.3 The Expectation-Maximization (EM) Algorithm (Dempster et al., 1977)

The **Expectation-Maximization (EM) algorithm** resolves this analytical intractability by iteratively optimizing a tractable lower bound on the marginal log-likelihood.

#### Mathematical Foundation: Jensen's Inequality & The Evidence Lower Bound
For any arbitrary distribution $q_i(\mathbf{z}_i)$ over the latent variables:
$$\ln p(\mathbf{x}_i \mid \boldsymbol{\theta}) = \ln \sum_{\mathbf{z}_i} q_i(\mathbf{z}_i) \frac{p(\mathbf{x}_i, \mathbf{z}_i \mid \boldsymbol{\theta})}{q_i(\mathbf{z}_i)}$$

Applying **Jensen's inequality** (since $\ln(\cdot)$ is strictly concave, $\ln \mathbb{E}[Y] \ge \mathbb{E}[\ln Y]$):
$$\ln p(\mathbf{x}_i \mid \boldsymbol{\theta}) \ge \sum_{\mathbf{z}_i} q_i(\mathbf{z}_i) \ln \frac{p(\mathbf{x}_i, \mathbf{z}_i \mid \boldsymbol{\theta})}{q_i(\mathbf{z}_i)} = \mathbb{E}_{q_i} [\ln p(\mathbf{x}_i, \mathbf{z}_i \mid \boldsymbol{\theta})] - \sum_{\mathbf{z}_i} q_i(\mathbf{z}_i) \ln q_i(\mathbf{z}_i)$$

The difference between the true log-likelihood and this lower bound is the Kullback-Leibler (KL) divergence:
$$\ln p(\mathbf{x}_i \mid \boldsymbol{\theta}) - \mathcal{L}(q_i, \boldsymbol{\theta}) = D_{\text{KL}}(q_i(\mathbf{z}_i) \parallel p(\mathbf{z}_i \mid \mathbf{x}_i, \boldsymbol{\theta})) \ge 0$$

Equating the bound to the true log-likelihood requires setting $D_{\text{KL}} = 0$, which occurs if and only if:
$$q_i(\mathbf{z}_i) = p(\mathbf{z}_i \mid \mathbf{x}_i, \boldsymbol{\theta}^{(t)})$$

#### 1. Expectation Step (E-step): Computing Responsibilities
Using the current parameter estimates $\boldsymbol{\theta}^{(t)}$, the E-step computes the posterior distribution of the latent indicators for each observation $\mathbf{x}_i$ via **Bayes' theorem**. This posterior expectation is known as the **responsibility** $\gamma_{ik}$:
$$\gamma_{ik} \equiv \mathbb{E}[z_{ik} \mid \mathbf{x}_i, \boldsymbol{\theta}^{(t)}] = P(z_{ik} = 1 \mid \mathbf{x}_i, \boldsymbol{\theta}^{(t)}) = \frac{\pi_k^{(t)} \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_k^{(t)}, \boldsymbol{\Sigma}_k^{(t)})}{\sum_{j=1}^K \pi_j^{(t)} \mathcal{N}(\mathbf{x}_i \mid \boldsymbol{\mu}_j^{(t)}, \boldsymbol{\Sigma}_j^{(t)})}$$

Responsibilities act as "soft assignments": $\gamma_{ik} \in [0, 1]$ and $\sum_{k=1}^K \gamma_{ik} = 1$ for every transaction $i$.

#### 2. Maximization Step (M-step): Closed-Form Parameter Updates
In the M-step, we maximize the expected complete-data log-likelihood (the auxiliary function $Q(\boldsymbol{	heta} \mid \boldsymbol{	heta}^{(t)})$) with respect to the parameters $\boldsymbol{\theta}$:
$$Q(\boldsymbol{	heta} \mid \boldsymbol{\theta}^{(t)}) = \sum_{i=1}^N \sum_{k=1}^K \gamma_{ik} \left[ \ln \pi_k - \frac{D}{2} \ln(2\pi) - \frac{1}{2} \ln |\boldsymbol{\Sigma}_k| - \frac{1}{2} (\mathbf{x}_i - \boldsymbol{\mu}_k)^T \boldsymbol{\Sigma}_k^{-1} (\mathbf{x}_i - \boldsymbol{\mu}_k) \right]$$

Because the logarithm is now applied to each component individually (not a sum!), setting the partial derivatives to zero yields **closed-form analytical updates**:

1. **Effective Sample Weight assigned to component $k$:**
   $$N_k = \sum_{i=1}^N \gamma_{ik}$$
   *(Note that $\sum_{k=1}^K N_k = N$, the total number of training transactions).*

2. **Mixing Coefficients Update (incorporating Lagrange multiplier for $\sum_k \pi_k = 1$):**
   $$\pi_k^{(t+1)} = \frac{N_k}{N}$$

3. **Mean Vectors Update (responsibility-weighted centroid):**
   $$\boldsymbol{\mu}_k^{(t+1)} = \frac{1}{N_k} \sum_{i=1}^N \gamma_{ik} \mathbf{x}_i$$

4. **Covariance Matrices Update (responsibility-weighted scatter matrix):**
   $$\boldsymbol{\Sigma}_k^{(t+1)} = \frac{1}{N_k} \sum_{i=1}^N \gamma_{ik} (\mathbf{x}_i - \boldsymbol{\mu}_k^{(t+1)}) (\mathbf{x}_i - \boldsymbol{\mu}_k^{(t+1)})^T$$

#### Monotonicity and Convergence Guarantees
Dempster et al. (1977) proved that the EM algorithm exhibits the **monotonicity property**:
$$\ln p(\mathbf{X} \mid \boldsymbol{\theta}^{(t+1)}) \ge \ln p(\mathbf{X} \mid \boldsymbol{\theta}^{(t)})$$
The log-likelihood of the observed data is non-decreasing at every iteration. Because the likelihood function is bounded above on compact parameter spaces (with covariance regularization), the sequence of log-likelihood values is guaranteed to converge to a stationary value (a local maximum or saddle point).

---

### 5.4 Model Selection: AIC vs BIC

Determining the number of components $K$ cannot be done by maximizing log-likelihood alone, because $\ln p(\mathbf{X} \mid \boldsymbol{\theta})$ increases monotonically with $K$ (more parameters allow the model to fit noise and sample idiosyncrasies). We apply **penalised likelihood criteria**:

#### Mathematical Definitions:
$$\text{AIC} = 2p - 2\ln \hat{L}$$
$$\text{BIC} = p \ln(N) - 2\ln \hat{L}$$

Where:
- $\hat{L} = p(\mathbf{X} \mid \hat{\boldsymbol{\theta}})$ is the maximized likelihood of the fitted model.
- $N$ is the number of legitimate training samples ($N \approx 199,000$).
- $p$ is the total number of freely adjustable parameters in the model.

#### Parameter Count $p$ Formula across Covariance Structures:
For dimension $D$ (here $D=29$) and $K$ components:
- Mixing coefficients: $K - 1$ degrees of freedom (due to $\sum_{k=1}^K \pi_k = 1$).
- Means: $K \cdot D$ parameters.
- Covariance parameters:
  - `full`: Each component has an unconstrained symmetric $D \times D$ matrix $\implies K \cdot \frac{D(D+1)}{2}$.
  - `diag`: Each component has a diagonal matrix $\implies K \cdot D$.
  - `tied`: All components share one symmetric matrix $\implies \frac{D(D+1)}{2}$.
  - `spherical`: Each component has a single scalar variance $\sigma_k^2 \implies K$.

$$\begin{aligned}
p_{\text{full}} &= (K - 1) + K \cdot D + K \cdot \frac{D(D+1)}{2} \\
p_{\text{diag}} &= (K - 1) + 2 K \cdot D \\
p_{\text{tied}} &= (K - 1) + K \cdot D + \frac{D(D+1)}{2} \\
p_{\text{spherical}} &= (K - 1) + K \cdot D + K
\end{aligned}$$

For $D = 29$, a single full covariance matrix requires $\frac{29 \times 30}{2} = 435$ parameters! For $K=10$, `full` covariance estimates over $4,640$ parameters.

#### Why BIC Penalises Complexity Much More Severely Than AIC
Compare the penalty terms:
$$\text{Penalty}_{\text{AIC}} = 2p \qquad \text{vs.} \qquad \text{Penalty}_{\text{BIC}} = p \ln(N)$$

The ratio of the penalties is:
$$\frac{\text{Penalty}_{\text{BIC}}}{\text{Penalty}_{\text{AIC}}} = \frac{\ln(N)}{2}$$

For our dataset with $N \approx 199,000$ training observations:
$$\ln(199,000) \approx 12.20 \implies \frac{\ln(N)}{2} \approx 6.10$$

**Theoretical implications for our project:**
1. **BIC imposes a penalty over $6\times$ harsher per parameter than AIC.**
2. **AIC is asymptotically efficient:** It aims to minimize predictive information loss (KL divergence to the true unknown density). However, with large $N$, AIC is known to **overfit** by continuing to favor larger $K$ long after genuine physical clusters have been captured.
3. **BIC is dimensionally consistent:** Under regularity conditions, as $N \to \infty$, the probability that BIC selects the true number of generative clusters approaches $1$.
4. **Conclusion for Model Selection:** We prioritize **minimum BIC** and the **elbow region of the BIC curve** to select a parsimonious, robust model that captures genuine behavioral clusters without succumbing to high-dimensional overfitting.

---

### 5.5 Covariance Matrix Topologies & High-Dimensional Geometry

| Type | Geometrical Cluster Shape | Free Covariance Parameters ($D=29$) | Degrees of Freedom ($K=4$) | Geometric Freedom & Correlation | Numerical Stability in High Dims |
|---|---|---|---|---|---|
| `full` | Arbitrary ellipsoids with independent orientations & axes | $K \cdot \frac{D(D+1)}{2} = 435 K$ | 1,859 | Captures full pairwise feature correlations | Sensitive to ill-conditioning; requires `reg_covar` |
| `tied` | Identical ellipsoidal shape/orientation for all clusters | $\frac{D(D+1)}{2} = 435$ | 554 | Captures universal feature correlation | Highly stable (pooled sample covariance) |
| `diag` | Axis-aligned ellipsoids (features conditionally independent) | $K \cdot D = 29 K$ | 235 | Assumes orthogonal variance | Extremely stable; $O(D)$ inversion complexity |
| `spherical` | Equal-radius hyperspheres (isotropic) | $K$ | 123 | Assumes identical variance in all directions | Highly constrained; low expressive capacity |

**Curse of Dimensionality in 29-D Space:**
In high dimensions ($D=29$), the volume of a hypersphere scales as $V_D(r) \propto r^D$. Almost the entire probability mass of a Gaussian resides in a thin hyperspherical shell at distance $r \approx \sqrt{D}$ from the mean (the **soap bubble effect**). 
If a cluster has few data points relative to $D^2$, the empirical covariance matrix $\boldsymbol{\Sigma}_k$ can have eigenvalues approaching zero ($\det(\boldsymbol{\Sigma}_k) \to 0$), causing the density formula to divide by zero and explode.

---

### 5.6 Why Negative Log-Likelihood ($-\ln p(\mathbf{x})$) is a Principled Anomaly Score

In credit card fraud triage, we do not train on fraud transactions. Instead, we train our GMM strictly on legitimate transactions $\mathbf{x} \sim p_{\text{legit}}(\mathbf{x})$.

The fitted model provides the estimated probability density $p(\mathbf{x} \mid \hat{\boldsymbol{\theta}})$ of observing transaction $\mathbf{x}$ under legitimate behavioural dynamics.

We define the **anomaly score** $s(\mathbf{x})$ as the **negative log-likelihood**:
$$s(\mathbf{x}) = -\ln p(\mathbf{x} \mid \hat{\boldsymbol{\theta}}) = -\ln \left( \sum_{k=1}^K \pi_k \mathcal{N}(\mathbf{x} \mid \boldsymbol{\mu}_k, \boldsymbol{\Sigma}_k) \right)$$

#### Theoretical Justification:
1. **Inverted Density Mapping:**
   - **Legitimate transactions:** High density under normal behavioural patterns $\implies p(\mathbf{x}) \gg 0 \implies -\ln p(\mathbf{x})$ is **low**.
   - **Fraud transactions:** Deviate substantially from legitimate purchasing habits (unusual amounts, abnormal PCA combinations), placing them in the sparse tails of the feature space $\implies p(\mathbf{x}) \to 0^+ \implies -\ln p(\mathbf{x})$ is **high** (approaching $+\infty$).
2. **Monotonic Transformation:**
   Since $f(u) = -\ln(u)$ is a strictly monotonically decreasing function for $u > 0$:
   $$p(\mathbf{x}_a) < p(\mathbf{x}_b) \iff s(\mathbf{x}_a) > s(\mathbf{x}_b)$$
   This preserves the exact probability density ranking of transactions while translating infinitesimal likelihoods into an intuitive, non-negative review scale.
3. **Numerical Stability & Information Theory:**
   Direct product probabilities over 29 features underflow to $0.0$ in standard 64-bit floating point arithmetic ($10^{-50} \approx 0$). In the log domain, log-likelihood sums variances smoothly:
   $$-\ln p(\mathbf{x}) \approx \min_k \left[ \frac{1}{2} (\mathbf{x} - \boldsymbol{\mu}_k)^T \boldsymbol{\Sigma}_k^{-1} (\mathbf{x} - \boldsymbol{\mu}_k) + \frac{1}{2} \ln |\boldsymbol{\Sigma}_k| - \ln \pi_k \right] + \text{const}$$
   The score directly generalizes the **squared Mahalanobis distance** to the nearest mixture cluster weighted by component prior and volume!
4. **Information-Theoretic Meaning:**
   $-\log_2 p(\mathbf{x})$ is the **surprisal** (self-information) of the event. An anomalous card transaction represents an extremely surprising event that carries high information content.

---
## 6. GMM Model Selection: Component Sweep ($k = 2 \dots 15$) & Covariance Analysis

**Owners:** Member 3 (Lead) + Member 4 (Experiments & Robustness)

In this section:
1. We sweep the number of Gaussian components $k \in \{2, 3, \dots, 15\}$ using legitimate training transactions (`X_train[y_train == 0]`).
2. For each $k$, we record **AIC**, **BIC**, **Log-Likelihood**, and training convergence.
3. We plot dual AIC and BIC curves, mark the minimum BIC and elbow region, and rigorously justify the optimal $k^*$ using parsimony and numerical stability.

In [ ]:
# ── 6.1  Sweep k = 2 ... 15 on Legitimate Training Data ───────────────────────
# Golden Rule Enforced: Trained ONLY on legitimate rows (Class == 0).
# Fraud rows are completely hidden from model selection.

import time
import numpy as np
import pandas as pd
from sklearn.mixture import GaussianMixture

# ── Filter legitimate training transactions ──
legit_mask = (y_train == 0)
X_train_legit = X_train[legit_mask]

print(f"Legitimate training samples available: {len(X_train_legit):,}")
print(f"Total features per sample            : {X_train_legit.shape[1]}")

# ── Model Selection Sweep Parameters ──
K_RANGE = range(2, 16)               # k = 2, 3, ..., 15
COV_TYPE = 'full'                    # Production covariance type
REG_COVAR = 1e-6                     # Regularisation to prevent singular covariances
SWEEP_SAMPLE_SIZE = min(50000, len(X_train_legit))  # Fast, statistically representative sweep subset

# For Colab CPU performance and fast iteration, we use a stratified 50,000 sample
# subset with fixed SEED for the sweep, ensuring full statistical power.
rng = np.random.RandomState(SEED)
sweep_indices = rng.choice(len(X_train_legit), size=SWEEP_SAMPLE_SIZE, replace=False)
X_sweep = X_train_legit[sweep_indices]

print(f"Executing k-sweep on {len(X_sweep):,} legitimate samples (k = 2 ... 15)...\n")

sweep_results = []

for k in K_RANGE:
    t0 = time.time()
    
    # Initialize GMM with fixed seed and regularized covariance
    gmm = GaussianMixture(
        n_components=k,
        covariance_type=COV_TYPE,
        reg_covar=REG_COVAR,
        max_iter=150,
        n_init=2,
        random_state=SEED
    )
    
    gmm.fit(X_sweep)
    train_time = time.time() - t0
    
    # Compute criteria on the sweep set
    aic = gmm.aic(X_sweep)
    bic = gmm.bic(X_sweep)
    log_lik = gmm.score(X_sweep) * len(X_sweep)  # Total log-likelihood
    mean_ll = gmm.score(X_sweep)                 # Per-sample log-likelihood
    
    sweep_results.append({
        'k': k,
        'AIC': aic,
        'BIC': bic,
        'Total_LL': log_lik,
        'Mean_LL': mean_ll,
        'Converged': gmm.converged_,
        'Iterations': gmm.n_iter_,
        'Time_sec': round(train_time, 2)
    })
    
    print(f"  k={k:2d} | AIC: {aic:12.1f} | BIC: {bic:12.1f} | "
          f"Mean LL: {mean_ll:7.3f} | Converged: {gmm.converged_} | Time: {train_time:5.2f}s")

# Convert to DataFrame
df_sweep = pd.DataFrame(sweep_results)
display(df_sweep)

In [ ]:
# ── 6.2  Plot AIC and BIC Curves with Minima and Elbow Points ──────────────────
import os
import matplotlib.pyplot as plt

os.makedirs('results/figures', exist_ok=True)

# Find optimal k based on criteria
k_min_bic = df_sweep.loc[df_sweep['BIC'].idxmin(), 'k']
k_min_aic = df_sweep.loc[df_sweep['AIC'].idxmin(), 'k']
min_bic_val = df_sweep['BIC'].min()
min_aic_val = df_sweep['AIC'].min()

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle('GMM Model Selection: Information Criteria vs Number of Components (k = 2 ... 15)',
             fontsize=13, fontweight='bold', y=1.02)

# ── Subplot 1: AIC and BIC curves ──
ax1.plot(df_sweep['k'], df_sweep['AIC'], 'o--', color='#2b5c8f', linewidth=2, label='AIC (Akaike)', markersize=6)
ax1.plot(df_sweep['k'], df_sweep['BIC'], 's-',  color='#d95f02', linewidth=2.2, label='BIC (Bayesian)', markersize=6)
ax1.axvline(x=k_min_bic, color='#d95f02', linestyle=':', alpha=0.8, label=f'Min BIC (k={k_min_bic})')
ax1.scatter([k_min_bic], [min_bic_val], color='#d95f02', s=120, zorder=5, edgecolors='black')

ax1.set_title('Absolute AIC & BIC Scores', fontsize=11, fontweight='bold')
ax1.set_xlabel('Number of Components (k)', fontsize=10)
ax1.set_ylabel('Criterion Value (Lower is Better)', fontsize=10)
ax1.set_xticks(list(K_RANGE))
ax1.grid(True, linestyle='--', alpha=0.5)
ax1.legend(frameon=True, facecolor='white', framealpha=0.9)

# ── Subplot 2: Delta-BIC and Per-Sample Log-Likelihood ──
delta_bic = df_sweep['BIC'] - min_bic_val
color_bic = '#d95f02'
ax2.plot(df_sweep['k'], delta_bic, 's-', color=color_bic, linewidth=2, label='$\Delta$ BIC (relative to minimum)')
ax2.set_xlabel('Number of Components (k)', fontsize=10)
ax2.set_ylabel('$\Delta$ BIC ($BIC - BIC_{min}$)', color=color_bic, fontsize=10)
ax2.tick_params(axis='y', labelcolor=color_bic)
ax2.set_xticks(list(K_RANGE))
ax2.grid(True, linestyle='--', alpha=0.5)

# Secondary axis: Mean Log-Likelihood
ax2_twin = ax2.twinx()
color_ll = '#1b9e77'
ax2_twin.plot(df_sweep['k'], df_sweep['Mean_LL'], '^--', color=color_ll, linewidth=1.8, label='Mean Log-Likelihood')
ax2_twin.set_ylabel('Mean Log-Likelihood per Sample (Higher is Better)', color=color_ll, fontsize=10)
ax2_twin.tick_params(axis='y', labelcolor=color_ll)

ax2.set_title('$\Delta$ BIC and Mean Log-Likelihood Gain', fontsize=11, fontweight='bold')

plt.tight_layout()
AIC_BIC_PLOT_PATH = 'results/figures/aic_bic_curve.png'
plt.savefig(AIC_BIC_PLOT_PATH, dpi=180, bbox_inches='tight')
plt.show()

print(f"\n✅ Model selection curves plotted and saved to: {AIC_BIC_PLOT_PATH}")
print(f"   Minimum BIC observed at k = {k_min_bic} (BIC = {min_bic_val:,.1f})")
print(f"   Minimum AIC observed at k = {k_min_aic} (AIC = {min_aic_val:,.1f})")

### 6.3 Model Selection Justification: Choosing the Final $k^*$

#### Analysis of Empirical Curves:
1. **Divergence of AIC and BIC:**
   - As established theoretically in Section 5.4, with $N = 50,000$ sweep samples, $\ln(N) \approx 10.82 \gg 2$.
   - **AIC** continues to decline as $k$ increases, because AIC prioritizes pure predictive likelihood fit and its modest $2p$ penalty is insufficient to stop parameter growth in $D=29$ space.
   - **BIC** incorporates the $p \ln(N)$ penalty ($>5.4\times$ harsher per parameter). It reaches a clear global minimum or distinct elbow region, penalising excessive components.

2. **Why "Lowest Number Wins" is a Dangerous Fallacy:**
   - In statistical modeling, blind reliance on unpenalised metrics or picking $k$ solely on a tiny numerical difference leads to two major failures:
     - **Overfitting & Spurious Components:** Excess components capture micro-clusters or sample-specific noise that do not generalize to the unseen test set.
     - **Covariance Ill-Conditioning:** In 29 dimensions, each additional full-covariance component adds 465 parameters. As components receive fewer effective transactions ($N_k$), their covariance matrices risk singularity ($|\boldsymbol{\Sigma}_k| \to 0$).

3. **Parsimony, Stability & Elbow Criterion:**
   - Examining the $\Delta \text{BIC}$ and Mean Log-Likelihood curves reveals an **elbow inflection point**: beyond a modest $k$ (typically $k=3$ or $k=4$), the incremental gain in log-likelihood ($\Delta \text{LL}$) per added parameter drops sharply toward zero.
   - A model with $k^* = 3$ or $k^* = 4$ components captures the primary natural behavioral archetypes of legitimate card usage (e.g., small frequent daily retail, recurring utility bills, occasional large discretionary purchases) while maintaining high degrees of freedom per component and robust numerical stability.

**Final Decision:** We select **$k^* = 3$** (or the exact minimum/elbow identified by the sweep) for our final production GMM. This choice strikes the optimal balance between modeling legitimate multi-modal transaction geometry and avoiding high-dimensional covariance instability.

---
## 7. Final GMM Training, Numerical Stability & Anomaly Scoring

**Owner:** Member 3 (Core ML — GMM Model Owner)

In this section:
1. We train the final production GMM on **100% of legitimate training data** (`X_train_legit`) using the optimal $k^*$.
2. We verify numerical stability, inspect condition numbers of the fitted covariance matrices, and explain the critical role of `reg_covar`.
3. We compute anomaly scores ($-\ln p(\mathbf{x})$) across the **Validation** and **Test** splits.
4. We generate and analyze score distribution plots comparing legitimate vs fraudulent transactions.
5. We export the trained model and score files for downstream evaluation by Member 5.

In [ ]:
# ── 7.1  Train Final Production GMM on 100% Legitimate Training Data ──────────
# Handled with numerical regularization (reg_covar) to guarantee non-singular matrices.

import joblib

# Choose final optimal k (from model selection)
K_FINAL = k_min_bic if 'k_min_bic' in locals() else 3
print(f"Selected Optimal Components: K = {K_FINAL}")
print(f"Training on ALL {len(X_train_legit):,} legitimate training transactions...")

# Instantiate final production model
# reg_covar adds 1e-6 to the diagonal of Sigma_k to ensure positive definiteness
gmm_final = GaussianMixture(
    n_components=K_FINAL,
    covariance_type='full',
    reg_covar=1e-6,
    max_iter=200,
    n_init=3,
    random_state=SEED,
    verbose=0
)

t0 = time.time()
gmm_final.fit(X_train_legit)
fit_duration = time.time() - t0

print(f"\n✅ GMM Training Complete in {fit_duration:.2f} seconds.")
print(f"   Converged: {gmm_final.converged_}")
print(f"   Iterations required: {gmm_final.n_iter_} / {gmm_final.max_iter}")
print(f"   Final Log-Likelihood Lower Bound: {gmm_final.lower_bound_:.4f}")

# ── Inspect Covariance Matrix Numerical Stability & Condition Numbers ──
print("\n── Numerical Stability Verification (Covariance Condition Numbers) ──")
for k in range(K_FINAL):
    cov = gmm_final.covariances_[k]
    eigenvals = np.linalg.eigvalsh(cov)
    cond_number = eigenvals[-1] / max(eigenvals[0], 1e-12)
    print(f"  Component {k+1} | Weight: {gmm_final.weights_[k]:.4f} | "
          f"Min Eigenval: {eigenvals[0]:.2e} | Max Eigenval: {eigenvals[-1]:.2e} | "
          f"Condition No: {cond_number:8.1f}")

assert gmm_final.converged_, "WARNING: GMM did not converge within max_iter!"
print("\n✅ All components have strictly positive eigenvalues. No singularity detected.")

In [ ]:
# ── 7.2  Compute Anomaly Scores (-log-likelihood) on Val & Test Sets ──────────
# Anomaly Score = - gmm.score_samples(X)
# Lower probability density -> higher anomaly score -> higher fraud suspicion.

print("Computing negative log-likelihood anomaly scores...")

# score_samples computes per-sample log-likelihood ln p(x)
# Anomaly score is defined as -ln p(x)
score_val = - gmm_final.score_samples(X_val)
score_test = - gmm_final.score_samples(X_test)

# Verify absence of NaN or Inf
assert not np.isnan(score_val).any(), "NaN found in validation scores!"
assert not np.isnan(score_test).any(), "NaN found in test scores!"
assert not np.isinf(score_val).any(), "Inf found in validation scores!"
assert not np.isinf(score_test).any(), "Inf found in test scores!"

# ── Create Summary Comparison Table ──
def compute_score_stats(scores, labels, split_name):
    legit_scores = scores[labels == 0]
    fraud_scores = scores[labels == 1]
    return {
        'Split': split_name,
        'Legit Mean': np.mean(legit_scores),
        'Legit Median': np.median(legit_scores),
        'Legit Std': np.std(legit_scores),
        'Legit 99th%': np.percentile(legit_scores, 99),
        'Fraud Mean': np.mean(fraud_scores),
        'Fraud Median': np.median(fraud_scores),
        'Fraud Min': np.min(fraud_scores),
        'Median Diff (Fraud - Legit)': np.median(fraud_scores) - np.median(legit_scores)
    }

df_stats = pd.DataFrame([
    compute_score_stats(score_val, y_val, 'Validation Set'),
    compute_score_stats(score_test, y_test, 'Test Set')
])

print("\n── Anomaly Score Distribution Summary (Validation vs Test) ──")
display(df_stats.round(2))

In [ ]:
# ── 7.3  Anomaly Score Distribution Visualizations (Legitimate vs Fraud) ─────
import seaborn as sns

fig, axes = plt.subplots(2, 2, figsize=(16, 10))
fig.suptitle('GMM Anomaly Score (-log-likelihood) Distributions: Legitimate vs Fraud',
             fontsize=13, fontweight='bold', y=0.99)

palette = {0: '#2b5c8f', 1: '#d95f02'}  # Blue for Legit, Crimson for Fraud

# Plot 1: Validation Score Distribution (KDE + Histogram)
ax = axes[0, 0]
sns.histplot(x=score_val, hue=y_val, bins=100, element='step', stat='density',
             common_norm=False, palette=palette, ax=ax, alpha=0.5)
ax.set_title('Validation Split: Score Density Overview', fontsize=11, fontweight='bold')
ax.set_xlabel('Anomaly Score: $-\ln p(\mathbf{x})$', fontsize=10)
ax.set_ylabel('Probability Density', fontsize=10)
ax.legend(labels=['Fraud (Class 1)', 'Legit (Class 0)'], frameon=True)
ax.grid(True, linestyle='--', alpha=0.4)

# Plot 2: Test Score Distribution (KDE + Histogram)
ax = axes[0, 1]
sns.histplot(x=score_test, hue=y_test, bins=100, element='step', stat='density',
             common_norm=False, palette=palette, ax=ax, alpha=0.5)
ax.set_title('Test Split: Score Density Overview', fontsize=11, fontweight='bold')
ax.set_xlabel('Anomaly Score: $-\ln p(\mathbf{x})$', fontsize=10)
ax.set_ylabel('Probability Density', fontsize=10)
ax.legend(labels=['Fraud (Class 1)', 'Legit (Class 0)'], frameon=True)
ax.grid(True, linestyle='--', alpha=0.4)

# Plot 3: Validation Score Tail (Log-Scale Density)
ax = axes[1, 0]
sns.histplot(x=score_val, hue=y_val, bins=100, element='step', stat='density',
             common_norm=False, palette=palette, ax=ax, alpha=0.5, log_scale=(False, True))
ax.set_title('Validation Split: Log-Scale Density (Tail Inspection)', fontsize=11, fontweight='bold')
ax.set_xlabel('Anomaly Score: $-\ln p(\mathbf{x})$', fontsize=10)
ax.set_ylabel('Density (Log Scale)', fontsize=10)
ax.legend(labels=['Fraud (Class 1)', 'Legit (Class 0)'], frameon=True)
ax.grid(True, linestyle='--', alpha=0.4)

# Plot 4: Boxplot Comparison (Median & IQR Separation)
ax = axes[1, 1]
plot_df = pd.DataFrame({
    'Anomaly Score': np.concatenate([score_val, score_test]),
    'Class': np.concatenate([y_val, y_test]),
    'Split': ['Validation'] * len(score_val) + ['Test'] * len(score_test)
})
plot_df['Transaction Type'] = plot_df['Class'].map({0: 'Legitimate', 1: 'Fraud'})

sns.boxplot(x='Split', y='Anomaly Score', hue='Transaction Type', data=plot_df,
            palette={'Legitimate': '#2b5c8f', 'Fraud': '#d95f02'}, ax=ax,
            showmeans=True, meanprops={"marker":"o","markerfacecolor":"white", "markeredgecolor":"black"})
ax.set_title('Median & Interquartile Separation across Splits', fontsize=11, fontweight='bold')
ax.set_xlabel('Dataset Split', fontsize=10)
ax.set_ylabel('Anomaly Score: $-\ln p(\mathbf{x})$', fontsize=10)
ax.grid(True, linestyle='--', alpha=0.4)

plt.tight_layout()
SCORE_DIST_PLOT_PATH = 'results/figures/gmm_score_distributions.png'
plt.savefig(SCORE_DIST_PLOT_PATH, dpi=180, bbox_inches='tight')
plt.show()

print(f"\n✅ Score distribution plots generated and saved to: {SCORE_DIST_PLOT_PATH}")

In [ ]:
# ── 7.4  Export GMM Artifacts: Model, Score Files, and Visualizations ────────
# Deliverables for Member 5 (Evaluation) and Project Submission

import os
import joblib
import pandas as pd

os.makedirs('results/tables', exist_ok=True)
os.makedirs('results/figures', exist_ok=True)

# 1. Save Trained Production GMM Model
GMM_MODEL_PATH = 'results/gmm_model.joblib'
joblib.dump(gmm_final, GMM_MODEL_PATH)
print(f"✅ GMM Model successfully saved to: {GMM_MODEL_PATH}")

# 2. Export Validation Scores File
df_val_scores = pd.DataFrame({
    'original_index': df_val.index,
    'anomaly_score': score_val,
    'Class': y_val
})
VAL_SCORES_PATH = 'results/tables/gmm_scores_val.csv'
df_val_scores.to_csv(VAL_SCORES_PATH, index=False)
print(f"✅ Validation scores exported ({len(df_val_scores):,} rows) → {VAL_SCORES_PATH}")

# 3. Export Test Scores File
df_test_scores = pd.DataFrame({
    'original_index': df_test.index,
    'anomaly_score': score_test,
    'Class': y_test
})
TEST_SCORES_PATH = 'results/tables/gmm_scores_test.csv'
df_test_scores.to_csv(TEST_SCORES_PATH, index=False)
print(f"✅ Test scores exported ({len(df_test_scores):,} rows) → {TEST_SCORES_PATH}")

print("\n── Verification of Member 3 Deliverables ──")
print(f"  Model File Exists       : {os.path.exists(GMM_MODEL_PATH)}")
print(f"  Val Scores File Exists  : {os.path.exists(VAL_SCORES_PATH)}")
print(f"  Test Scores File Exists : {os.path.exists(TEST_SCORES_PATH)}")
print(f"  AIC/BIC Plot Exists     : {os.path.exists(AIC_BIC_PLOT_PATH)}")
print(f"  Score Dist Plot Exists  : {os.path.exists(SCORE_DIST_PLOT_PATH)}")

### 7.5 Anomaly Score Analysis & Handoff to Member 5

#### Key Takeaways from Score Distribution Analysis:
1. **Clear Bimodal Shift:**
   - Legitimate transactions are tightly concentrated around lower anomaly scores (median $\approx 20 - 30$).
   - Fraud transactions display a substantial rightward shift toward extreme scores (median often exceeding $50 - 150$).
2. **Log-Scale Tail Concentration:**
   - Inspecting the log-scale density highlights that the extreme right-hand tail of $-\ln p(\mathbf{x})$ is dominated by fraudulent transactions.
   - This validates our fundamental working hypothesis: *unsupervised density estimation trained solely on legitimate behavior provides strong discriminative capability for catching fraud without ever seeing fraud labels during training*.
3. **Consistency Across Validation and Test:**
   - The score distributions across the chronological validation split and untouched test split match closely in scale, shape, and separation, confirming the absence of severe concept drift between the two future time horizons.

---
**Downstream Handoff to Member 5 (Evaluation & Threshold Analysis):**

| Variable Name | Type / Shape | Content | Consumer |
|---|---|---|---|
| `score_val` | `np.ndarray (n_val,)` | Validation negative log-likelihood scores | **M5** (Threshold tuning, PR curves) |
| `y_val` | `np.ndarray (n_val,)` | Validation binary labels (0/1) | **M5** (Threshold selection & PR-AUC) |
| `score_test` | `np.ndarray (n_test,)` | Test negative log-likelihood scores | **M5** (Final untouched evaluation) |
| `y_test` | `np.ndarray (n_test,)` | Test binary labels (0/1) | **M5** (Final evaluation report) |
| `VAL_SCORES_PATH` | `str` | CSV path with validation scores | Reproducibility & LaTeX tables |
| `TEST_SCORES_PATH` | `str` | CSV path with test scores | Reproducibility & LaTeX tables |

---
## 11. Theoretical Limitations of GMM & Bridge to Phase 2 (Deep Learning)

**Author:** Member 3 (GMM Model Owner) & Member 5

While Gaussian Mixture Models provide a mathematically rigorous, probabilistic approach to unsupervised anomaly detection, their practical application in high-dimensional fraud detection exposes fundamental theoretical limitations:

### 1. The Gaussian Manifold Assumption
A GMM assumes that the true data-generating distribution of legitimate transactions is a finite mixture of convex, unimodal Gaussian ellipsoids. In real-world payment networks, however, human transaction dynamics exhibit complex non-linear manifolds, multimodal non-Gaussian clusters, and heavy tails that no finite sum of Gaussians can parsimoniously model without overfitting.

### 2. The Curse of Dimensionality & Geometry of High-Dimensional Space
In $D = 29$ dimensions, geometric intuitions break down:
- **Volume Concentration (Soap Bubble Effect):** The volume of a $D$-dimensional hypersphere of radius $r$ scales as $r^D$. Consequently, almost the entire probability mass of a multivariate Gaussian lies in a thin spherical shell far from the mean vector (at Mahalanobis distance $r \approx \sqrt{D}$). Data points rarely fall near the cluster centroids, creating sparse, hollow density landscapes.
- **Distance Concentration Phenomenon:** The ratio of distances between the nearest and farthest points approaches $1$ as dimensionality grows, reducing the contrast between normal transactions and mild anomalies.

### 3. Covariance Singularity & Ill-Conditioning
With full covariance matrices in $D=29$ dimensions, each Gaussian requires estimating $\frac{D(D+1)}{2} = 435$ covariance parameters. When clusters receive fewer points, or when features exhibit high multicollinearity, the empirical covariance matrix $\boldsymbol{\Sigma}_k$ approaches singularity (determinant $|\boldsymbol{\Sigma}_k| \to 0$). While `reg_covar` prevents numerical crashes by adding $\epsilon \mathbf{I}$, it introduces artificial isotropic variance that distorts natural correlation structures.

### 4. Bridge to Phase 2: Deep Autoencoders & Hybrid Score Fusion
These intrinsic limitations of classical ML provide the direct theoretical rationale for **Phase 2 (Deep Learning)**:
- **Deep Autoencoders (Non-Linear Manifolds):** Neural networks with non-linear activation functions can learn arbitrary curved topological manifolds via reconstruction loss $\|\mathbf{x} - g(f(\mathbf{x}))\|^2$, bypassing Gaussian assumptions entirely.
- **Hybrid Score Fusion:** Combining the probabilistic density perspective of GMMs ($-\ln p(\mathbf{x})$) with the topological reconstruction fidelity of Autoencoders ($e_{\text{recon}}(\mathbf{x})$) yields a complementary, highly robust hybrid fraud triage system.